create database customer_behavior;
use customer_behavior;

SELECT * from customer limit 10;

SELECT COUNT(*)FROM customer;

DELIMITER //

CREATE PROCEDURE Customers()
BEGIN
    SELECT *
    FROM customer
    LIMIT 10;
END //

DELIMITER ;
call customers;

 -- total revenue generated by male vs female customers
 create view revenue_by_gender as
 select gender ,SUM(purchase_amount) AS Revenue
 FROM customer
 GROUP BY gender;
 
 -- which customers used a discount but still spent more than an average purchase amount?
 -- total count
 CREATE VIEW discount_high_spenders as
 SELECT count(customer_id) , sum(purchase_amount)
 from customer
 where discount_applied = 'Yes' 
 and purchase_amount >(select avg(purchase_amount) from customer);
 
 SELECT customer_id , purchase_amount
 from customer
 where discount_applied = 'Yes' 
 and purchase_amount >(select avg(purchase_amount) from customer);
 
 -- which are the top 5 products with the highest average review rating?

 select item_purchased as top5_products , round(avg(review_rating),1) as avg_rating 
 from customer
 group by item_purchased
 order by avg_rating desc
 limit 5;
 
 -- compare the average purchase amounts between standard and express shipping.

select shipping_type , round(avg(purchase_amount),2) from customer
where shipping_type in('Express','Standard')
group by shipping_type;

-- Do subscribed customers spend more? compare avg spend and total revenue between subscribers and non subcribers.

select subscription_status , count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend , round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status;

-- which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased ,concat(round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) *100,2) ,'%')as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new , returning and loyal based on their total number of previous purchases, 
-- and show the count of each segment


SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Occasional Buyer'
        WHEN previous_purchases BETWEEN 6 AND 15 THEN 'Frequent Buyer'
        ELSE 'Loyal Customer'
    END AS segment,
    COUNT(*) AS customers
FROM customer
GROUP BY segment
ORDER BY customers DESC;


-- what are the top 3 most purchased products within each category?

SELECT
    category,
    item_purchased,
    COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased
ORDER BY category, purchase_count DESC;

drop view customer_segment_summary




WITH product_sales AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY purchase_count DESC
           ) AS rn
    FROM product_sales
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE rn <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


SELECT
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- what is the revenue contribution of each age group?


WITH categorized_customers AS (
    SELECT 
        purchase_amount,
        CASE 
            WHEN age BETWEEN 18 AND 25 THEN '18-25' 
            WHEN age BETWEEN 26 AND 35 THEN '26-35' 
            WHEN age BETWEEN 36 AND 45 THEN '36-45' 
            WHEN age BETWEEN 46 AND 55 THEN '46-55' 
            ELSE '55+' 
        END AS age_group
    FROM customer
)
SELECT age_group, SUM(purchase_amount) AS revenue 
FROM categorized_customers
GROUP BY age_group 
ORDER BY revenue DESC;

 
 
  